name: Pipeline

on: [push]
env:
  APPLICATION_NAME: startupapp
jobs:
  lint:
    runs-on: ubuntu-18.04
    
        
  build_image:
    needs: [lint]
    runs-on: ubuntu-18.04
   
  
  test_image:
    needs: [build_image]
    runs-on: ubuntu-18.04
   
  
      
  deploy:
    needs: [test_image]
    runs-on: ubuntu-18.04
   
